- name: Kindo Playbook
  hosts: localhost

  pre_tasks:
    - name: Update apt cache
      become: true
      tags: update
      ansible.builtin.apt:
        update_cache: true

    - name: Update apt packages
      become: true
      tags: update
      ansible.builtin.apt:
        upgrade: full

  tasks:
    - name: Install apt packages
      tags: ["packages", "install"]
      ansible.builtin.include_tasks: tasks/packages.yaml

    - name: Create User Kindo
      tags: ['user', 'system']
      ansible.builtin.include_tasks: tasks/user.yaml

    - name: Prequsites
      tags: ["prerequisite"]
      ansible.builtin.include_tasks: tasks/prerequisite.yaml

    - name: Setup desktop environment
      tags: ["de", "system"]
      ansible.builtin.include_tasks: tasks/de.yaml

    - name: Setup Uart
      tags: ["uart"]
      ansible.builtin.include_tasks: tasks/uart.yaml

    - name: Setup boot animation - Plymouth
      tags: ["plymouth"]
      ansible.builtin.include_tasks: tasks/plymouth.yaml

    - name: Setup Kindo App
      tags: ["kindo-app"]
      ansible.builtin.include_tasks: tasks/kindo-app.yaml
