- name: Adding kindo user to docker group
  tags: ["docker"]
  become: true
  ansible.builtin.user:
    name: kindo
    groups: docker
    append: true

- name: Autostart Docker
  tags: ["docker"]
  become: true
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
    daemon_reload: true

- name: Autostart containerd
  tags: ["docker"]
  become: true
  ansible.builtin.systemd:
    name: containerd
    enabled: true
    state: started
    daemon_reload: true
