- name: "Install apt packages"
  become: true
  tags: ["packages", "install"]
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - xserver-xorg
    - xinit
    - x11-xserver-utils
    - xwallpaper
    - xserver-xorg-input-libinput
    - wget
    - curl
    - plymouth
    - plymouth-themes
    - stterm
    - suckless-tools
    - libasound-dev

- name: Install dwm package
  become: true
  tags: ["packages", "install"]
  ansible.builtin.uri:
    url: "http://pkg.kintechnology.io/dwm"
    dest: "/usr/local/bin/"
    mode: "0755"
    status_code:
      - 200
      - 304

- name: Install nocursor package
  become: true
  tags: ["packages", "install"]
  ansible.builtin.uri:
    url: "http://pkg.kintechnology.io/nocursor"
    dest: "/usr/local/bin/"
    mode: "0755"
    status_code:
      - 200
      - 304

- name: Install Docker Engine
  become: true
  tags: ["packages", "install"]
  ansible.builtin.shell: |
    set -o pipefail
    curl -fsSL https://get.docker.com | sh
  args:
    creates: /usr/bin/docker
    executable: /bin/bash
