- name: Ensure enable_uart=1 is present under the [all] block
  tags: ["uart"]
  become: true
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    regexp: '^enable_uart='
    line: 'enable_uart=1'
    insertafter: '\[all\]'
    state: present

- name: Ensure dtoverlay=uart3 is present under the [all] block
  tags: ["uart"]
  become: true
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    regexp: '^dtoverlay=uart3'
    line: 'dtoverlay=uart3'
    insertafter: '\[all\]'
    state: present

- name: Ensure dtoverlay=uart1 is present under the [all] block
  tags: ["uart"]
  become: true
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    regexp: '^dtoverlay=uart1'
    line: 'dtoverlay=uart1'
    insertafter: '\[all\]'
    state: present

- name: Pull kindo-uart-ws:0.1 image
  tags: ["uart"]
  become: true
  ansible.builtin.command: docker pull kintechnology/kindo-uart-ws:0.1

- name: Run kindo-uart-ws:0.1 container
  tags: ["uart"]
  become: true
  ansible.builtin.command: docker run --name kindo-uart-ws --device=/dev/ttyAMA3 --device=/dev/ttyS0 -d -p 3000:3000 kintechnology/kindo-uart-ws:0.1

- name: Ensure kindo-uart-ws is started on boot
  tags: ["uart"]
  become: true
  ansible.builtin.command: docker update --restart=always kindo-uart-ws
