- name: Create user kindo
  tags: ['user', 'system']
  become: true
  ansible.builtin.user:
    name: kindo
    state: present
    shell: /bin/bash
    groups: sudo
    append: true
    create_home: true
    home: /home/kindo
    password: "{{ 'kindo' | password_hash('sha512') }}"

- name: Create gettty service directory
  become: true
  tags: ["user", "system"]
  ansible.builtin.file:
    recurse: true
    path: /etc/systemd/system/getty@tty1.service.d/
    state: directory

- name: Create getty service override
  become: true
  tags: ["user", "system"]
  ansible.builtin.copy:
    dest: /etc/systemd/system/getty@tty1.service.d/override.conf
    mode: '0644'
    content: |
      [Service]
      ExecStart=
      ExecStart=-/sbin/agetty --autologin kindo --noclear %I $TERM

- name: Enable getty service
  become: true
  tags: ["user", "system"]
  ansible.builtin.systemd:
    name: getty@tty1.service
    daemon_reload: true
    enabled: true
